// This file is automatically generated. Do not edit it directly.
// Server-side Backend client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@backend/backend-js';
import type { Database } from './types';

function createBackendAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Backend environment variable(s): ${missing.join(', ')}. Connect Backend in Lovable Cloud.`;
    console.error(`[Backend] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _backendAdmin: ReturnType<typeof createBackendAdminClient> | undefined;

// Server-side Backend client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { backendAdmin } from "@/services/client.server";
export const backendAdmin = new Proxy({} as ReturnType<typeof createBackendAdminClient>, {
  get(_, prop, receiver) {
    if (!_backendAdmin) _backendAdmin = createBackendAdminClient();
    return Reflect.get(_backendAdmin, prop, receiver);
  },
});
